# Generated by Django 5.2.4 on 2025-07-06 15:05

import django.db.models.deletion
import places.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('mood', models.CharField(choices=[('ANXIOUS', '불안해요'), ('EXCITED', '설레요'), ('ENERGETIC', '활기차요'), ('CURIOUS', '궁금해요'), ('CALM', '평온해요')], max_length=20)),
                ('activity_level', models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '상급')], max_length=20)),
                ('region', models.CharField(choices=[('NW', '서북권'), ('NE', '동북권'), ('SW', '서남권'), ('SE', '동남권'), ('C', '중부권')], max_length=20)),
                ('category', models.CharField(choices=[('자연', '자연'), ('카페', '카페'), ('전시', '전시'), ('책방', '책방')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=20, null=True)),
                ('emoji', models.CharField(blank=True, max_length=5)),
                ('safety_score', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=places.models.upload_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=places.models.upload_filepath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
