# Generated by Django 4.2.23 on 2025-07-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('ANXIOUS', '불안해요'), ('ANGRY', '화나요'), ('ENERGETIC', '활기차요'), ('TIRED', '지쳤어요'), ('CALM', '평온해요'), ('EXCITED', '설레요')], max_length=10, null=True)),
                ('activity_level', models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '상급')], max_length=12, null=True)),
                ('region', models.CharField(choices=[('NW', '서북권'), ('NE', '동북권'), ('SW', '서남권'), ('SE', '동남권'), ('C', '중부권')], max_length=2, null=True)),
                ('liked_places', models.ManyToManyField(blank=True, related_name='liked_by', to='journeys.place')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
