# Generated by Django 4.2.23 on 2025-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '상급')], max_length=12, null=True),
        ),
    ]
