# Generated by Django 4.2.23 on 2025-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('NW', '서북권'), ('NE', '동북권'), ('SW', '서남권'), ('SE', '동남권'), ('C', '중부권')], max_length=2, null=True),
        ),
    ]
