# Generated by Django 4.2.23 on 2025-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '상급')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emotion',
            field=models.CharField(choices=[('ANXIOUS', '불안해요'), ('EXCITED', '설레요'), ('ENERGETIC', '활기차요'), ('CURIOUS', '궁금해요'), ('CALM', '평온해요')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('NW', '서북권'), ('NE', '동북권'), ('SW', '서남권'), ('SE', '동남권'), ('C', '중부권')], max_length=2, null=True),
        ),
    ]
