# Generated by Django 4.2.23 on 2025-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '__first__'),
        ('accounts', '0004_alter_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_places',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='journeys.place'),
        ),
    ]
